namespace GlavLib.SourceGenerators.Tests;

public partial class ServiceRegistrationSourceGeneratorTests
{
    public class Transient
    {
        [Fact]
        public void It_should_register_as_self()
        {
            //language=CSharp
            const string source = """
                                  using GlavLib.Abstractions.DI;
                                  
                                  namespace TestNamespace;

                                  [Transient]
                                  public sealed class TestClass
                                  {
                                  }
                                  """;
        
            var result = Run(source);

            //language=CSharp
            const string expected = """
                                    /// <auto-generated/>
                                    using Microsoft.Extensions.DependencyInjection;
                                    
                                    namespace GlavLib.SourceGenerators.Tests;
                                    
                                    public static class ServiceExtensions
                                    {
                                        public static void Add_GlavLib_SourceGenerators_Tests(this IServiceCollection services)
                                        {
                                            services.AddTransient<TestNamespace.TestClass>();
                                        }
                                    }
                                    """;
        
            Assert.Equal(expected, result, ignoreLineEndingDifferences: true);
        }
        
        [Fact]
        public void It_should_register_as_interface()
        {
            //language=CSharp
            const string source = """
                                  using GlavLib.Abstractions.DI;
                                  
                                  namespace TestNamespace;

                                  public interface ITest { }
                                  
                                  [Transient<ITest>]
                                  public sealed class TestClass
                                  {
                                  }
                                  """;
        
            var result = Run(source);

            //language=CSharp
            const string expected = """
                                    /// <auto-generated/>
                                    using Microsoft.Extensions.DependencyInjection;
                                    
                                    namespace GlavLib.SourceGenerators.Tests;
                                    
                                    public static class ServiceExtensions
                                    {
                                        public static void Add_GlavLib_SourceGenerators_Tests(this IServiceCollection services)
                                        {
                                            services.AddTransient<TestNamespace.ITest, TestNamespace.TestClass>();
                                        }
                                    }
                                    """;
        
            Assert.Equal(expected, result, ignoreLineEndingDifferences: true);
        }
    }
}