namespace GlavLib.SourceGenerators.Tests;

public partial class ServiceRegistrationSourceGeneratorTests
{
    public class DomainEventHandlers
    {
        [Fact]
        public void It_should_generate_domain_event_handler_registration()
        {
            //language=CSharp
            const string source = """
                                  using GlavLib.Abstractions.DI;
                                  using GlavLib.App.DomainEvents;

                                  namespace TestNamespace;

                                  public sealed class TestEvent : DomainEvent  { }

                                  [DomainEventHandler<TestEvent>]
                                  public sealed class TestEventHandler : DomainEventHandler<TestEvent>
                                  {
                                      protected override Task HandleAsync(TestEvent domainEvent, CancellationToken cancellationToken)
                                      {
                                          return Task.CompletedTask;
                                      }
                                  }
                                  """;

            var result = Run(source);

            //language=CSharp
            const string expected = """
                                    /// <auto-generated/>
                                    using Microsoft.Extensions.DependencyInjection;
                                    
                                    namespace GlavLib.SourceGenerators.Tests;
                                    
                                    public static class ServiceExtensions
                                    {
                                        public static void Add_GlavLib_SourceGenerators_Tests(this IServiceCollection services)
                                        {
                                            services.AddKeyedSingleton<GlavLib.App.DomainEvents.IDomainEventHandler, TestNamespace.TestEventHandler>(typeof(TestNamespace.TestEvent));
                                        }
                                    }
                                    """;

            Assert.Equal(expected, result, ignoreLineEndingDifferences: true);
        }
    }
}