namespace GlavLib.SourceGenerators.Tests;

public partial class ServiceRegistrationSourceGeneratorTests
{
    public class SingleInstance
    {
        [Fact]
        public void It_should_register_as_self()
        {
            //language=CSharp
            const string source = """
                                  using GlavLib.Abstractions.DI;
                                  
                                  namespace TestNamespace;

                                  [SingleInstance]
                                  public sealed class TestClass
                                  {
                                  }
                                  """;
        
            var result = Run(source);

            //language=CSharp
            const string expected = """
                                    /// <auto-generated/>
                                    using Microsoft.Extensions.DependencyInjection;

                                    namespace GlavLib.SourceGenerators.Tests;

                                    public static class ServiceExtensions
                                    {
                                        public static IServiceCollection Add_GlavLib_SourceGenerators_Tests(this IServiceCollection services)
                                        {
                                            services.AddSingleton<TestNamespace.TestClass>();
                                            return services;
                                        }
                                    }
                                    """;
        
            Assert.Equal(expected, result, ignoreLineEndingDifferences: true);
        }

        [Fact]
        public void It_should_register_as_self_keyed()
        {
            //language=CSharp
            const string source = """
                                  using GlavLib.Abstractions.DI;

                                  namespace TestNamespace;

                                  [SingleInstance(1)]
                                  public sealed class TestClass
                                  {
                                  }
                                  """;
        
            var result = Run(source);

            //language=CSharp
            const string expected = """
                                    /// <auto-generated/>
                                    using Microsoft.Extensions.DependencyInjection;

                                    namespace GlavLib.SourceGenerators.Tests;

                                    public static class ServiceExtensions
                                    {
                                        public static IServiceCollection Add_GlavLib_SourceGenerators_Tests(this IServiceCollection services)
                                        {
                                            services.AddKeyedSingleton<TestNamespace.TestClass>(1);
                                            return services;
                                        }
                                    }
                                    """;
        
            Assert.Equal(expected, result, ignoreLineEndingDifferences: true);
        }

        [Fact]
        public void It_should_register_as_interface()
        {
            //language=CSharp
            const string source = """
                                  using GlavLib.Abstractions.DI;
                                  
                                  namespace TestNamespace;

                                  public interface ITest { }

                                  [SingleInstance<ITest>]
                                  public sealed class TestClass
                                  {
                                  }
                                  """;
        
            var result = Run(source);

            //language=CSharp
            const string expected = """
                                    /// <auto-generated/>
                                    using Microsoft.Extensions.DependencyInjection;
                                    
                                    namespace GlavLib.SourceGenerators.Tests;
                                    
                                    public static class ServiceExtensions
                                    {
                                        public static IServiceCollection Add_GlavLib_SourceGenerators_Tests(this IServiceCollection services)
                                        {
                                            services.AddSingleton<TestNamespace.ITest, TestNamespace.TestClass>();
                                            return services;
                                        }
                                    }
                                    """;
        
            Assert.Equal(expected, result, ignoreLineEndingDifferences: true);
        }
        
        [Fact]
        public void It_should_register_as_interface_keyed()
        {
            //language=CSharp
            const string source = """
                                  using GlavLib.Abstractions.DI;

                                  namespace TestNamespace;

                                  public interface ITest { }

                                  [SingleInstance<ITest>("key"))]
                                  public sealed class TestClass
                                  {
                                  }
                                  """;
        
            var result = Run(source);

            //language=CSharp
            const string expected = """
                                    /// <auto-generated/>
                                    using Microsoft.Extensions.DependencyInjection;

                                    namespace GlavLib.SourceGenerators.Tests;

                                    public static class ServiceExtensions
                                    {
                                        public static IServiceCollection Add_GlavLib_SourceGenerators_Tests(this IServiceCollection services)
                                        {
                                            services.AddKeyedSingleton<TestNamespace.ITest, TestNamespace.TestClass>("key");
                                            return services;
                                        }
                                    }
                                    """;
        
            Assert.Equal(expected, result, ignoreLineEndingDifferences: true);
        }

    }
}